# Generated by Django 4.2.4 on 2023-09-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
