# Generated by Django 4.2.4 on 2023-09-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messages_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='content',
            new_name='message',
        ),
    ]
