# FROM  node  as build
# WORKDIR /app

# COPY ./frontend ./
# RUN npm install


# RUN npm run build --prod





FROM nginx:1.19.0-alpine

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY frontend/build /usr/share/nginx/html
# CMD ["nginx", "-g", "daemon off;"]

