FROM  node  as build
WORKDIR /app

COPY ./frontend ./






FROM nginx:1.19.0-alpine
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY  --from=build /app/frontend/build /usr/share/nginx/html
# CMD ["nginx", "-g", "daemon off;"]

