# Generated by Django 4.2.4 on 2023-09-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
