# Generated by Django 4.2.4 on 2023-09-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
