# Generated by Django 4.2.4 on 2023-08-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='caption',
        ),
    ]
