# Generated by Django 4.2.4 on 2023-08-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_fullname_myuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default='abba@gmail.com', max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
