# Generated by Django 4.2.4 on 2023-08-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_myuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_verifield',
            field=models.BooleanField(default=False),
        ),
    ]
