# Generated by Django 4.2.4 on 2023-08-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_myuser_is_verifield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_verifield',
            new_name='is_verified',
        ),
    ]
