# Generated by Django 4.2.4 on 2023-08-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userpreferences_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
