# Generated by Django 4.2.4 on 2023-08-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_images_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='images',
            field=models.ManyToManyField(related_name='user_profiles', to='users.images'),
        ),
    ]
