# Generated by Django 4.2.4 on 2023-08-31 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_followers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('user', 'followed_user')},
        ),
    ]
